name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info && gcloud auth configure-docker
    - name: Build the Base Docker image
      run: docker build . --file Dockerfile --tag gcr.io/cluster-171711/uqcs-frontend:${{ github.sha }} --tag gcr.io/cluster-171711/uqcs-frontend:latest && docker push gcr.io/cluster-171711/uqcs-frontend:${{ github.sha }} && docker push gcr.io/cluster-171711/uqcs-frontend:latest